### ISSUE TITLE
Show the Selected Students In the starting

### ISSUE THREAD

**Issue by gowtham3105** [CDC-IITDH/cdc-placement-website-frontend#118]
In the details page in admin show the selected students first and then the other students in alphabetically order. The cards in green color should be in the first since they are marked as selected.

![image](https://user-images.githubusercontent.com/66207607/196994561-8b9e6f3f-8dde-4bc0-853f-2285dfe64dad.png)

**Comment by harsh0620** [comment]
Hey @gowtham3105, Please assign me this task.

**Comment by harsh0620** [comment]
Please verify my email and provide the key.
E-Mail: harsh0111chandravanshi@gmail.com

**Comment by gowtham3105** [comment]
You need to set up the Backend and Frontend in your local machine. 
Backend Repo Link: https://github.com/CDC-IITDH/cdc-placement-website-backend

I can provide you with the env Files are these repos
